apiVersion: iot.ibm.com/v1
kind: IoT
metadata:
  name: {{ .Values.masapp.instanceid }}
  namespace: {{ .Values.masapp.namespace }}
  labels:
    mas.ibm.com/applicationId: iot
    mas.ibm.com/instanceId: {{ .Values.masapp.instanceid }}
    {{- include "ibm-masapp-iot.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2" 
spec:
  bindings:
    jdbc: system
    mongo: system
    kafka: system
