apiVersion: iot.ibm.com/v1
kind: IoTWorkspace
metadata:
  name: "{{ .Values.workspace.name }}"
  labels:
    mas.ibm.com/instanceId: "{{ .Values.masapp.instanceid }}"
    mas.ibm.com/workspaceId: "{{ .Values.masapp.workspaceid }}"
    mas.ibm.com/applicationId: "{{ .Values.masapp.appid }}"
    {{- include "ibm-masapp-iot.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3" 
spec: {}

